metadata:
  labels:
    some-label: some-label-value
    class: KubernetesDeclarativeAgentTest
  namespace: scm
spec:
  containers:
    - name: build
      image: hub.hobot.cc/builder/gradle-builder:0.2
      command:
      - cat
      tty: true
      env:
        - name: CONTAINER_ENV_VAR
          value: build
